seed: 42
device: "cuda:0"
data:
  root: "data"
  train_split: "processed/train.jsonl"
  val_split: "processed/val.jsonl"
  test_split: "processed/test.jsonl"
model:
  base: "meta-llama/Llama-3.2-3B-Instruct"
  lora: true
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.05
train:
  method: "dpo"        # or "sft"
  epochs: 3
  batch_size: 8
  lr: 3e-5
  grad_accum: 1
eval:
  metrics: ["rouge1","rougeL"]
